### ISSUE TITLE
TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'.  File "/DAE-AQA/util.py", line 27, in loss_function     rec_loss = alpha/((sigma**2)*MSE_loss(x, mu)). Here sigma is  a list, it can not do the operation **2. How to solve this question?

### ISSUE THREAD

**Issue by sulizhi** [InfoX-SEU/DAE_AQA#1]

**Comment by BaiMeiyingxue** [comment]
Hi, I encounter the same question, I don't understand the reason for the error. Is the loss function in the paper seems different from the [code](https://github.com/Luciferbobo/DAE-AQA/blob/0c92dcafdb096476ffa10471867ac7f6f29b9743/util.py#L25)?
![image](https://github.com/Luciferbobo/DAE-AQA/assets/53547009/669b6c71-9e59-46d5-982d-d68d3a7a5a62)

**Comment by yyren7** [comment]
same problem, maybe because of pytorch version or some other reason?

**Comment by Luciferbobo** [comment]
Thanks to everyone for your reminders. I sincerely apologize for the bug in the loss function. It seems that the util.py file was mistakenly uploaded with the debug scalar version during the organization process. Now, this bug has been fixed. In util.py, there are two versions of the loss function available: 1. loss_function() is a stable version that approximates linear regression. 2. loss_function_v2() corresponds to the original loss function in the research paper, as the variance effect may lead to unstable convergence during training, and it tends to yield little better performance compared to loss_function() after multiple training iterations.

**Comment by BaiMeiyingxue** [comment]
> Thanks to everyone for your reminders. I sincerely apologize for the bug in the loss function. It seems that the util.py file was mistakenly uploaded with the debug scalar version during the organization process. Now, this bug has been fixed. In util.py, there are two versions of the loss function available: 1. loss_function() is a stable version that approximates linear regression. 2. loss_function_v2() corresponds to the original loss function in the research paper, as the variance effect may lead to unstable convergence during training, and it tends to yield little better performance compared to loss_function() after multiple training iterations.

Hi,
thanks for your reply! I use the [loss function](https://github.com/Luciferbobo/DAE-AQA/blob/fc9037f3e875632e2863b22b33ddb994bdd3d21e/util.py#L26C5-L26C36) an error occurred 
]
```
Traceback (most recent call last):
  File "main_DAE-score-nsoftlabel.py", line 566, in <module>
    main(dataloaders, audio_net, evaluator, base_logger, dataset_config, config['MODEL'], args, model_type, ckpt_path,dae_model_pth)
  File "main_DAE-score-nsoftlabel.py", line 240, in main
    loss.backward()
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/torch/autograd/__init__.py", line 141, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "/home/zhangwenjuan/anaconda3/envs/evacuda11/lib/python3.8/site-packages/torch/autograd/__init__.py", line 50, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```
and I print the loss(torch[batch_size,]),

it seems that the function should return (rec_loss+sup_loss).sum() or (rec_loss+sup_loss).mean()?
