### ISSUE TITLE
Code for testing the models

### ISSUE THREAD

**Issue by NamburiSrinath** [InfoX-SEU/DAE_AQA#2]
Hi @Luciferbobo and @Bbchen229 

Thanks for the repo, it's super concise! 

I've a quick question -- I can download the `weights.rar` file but I can't find a test script in the repo which I can use to load the model and get results.

Thanks
Srinath

**Comment by Luciferbobo** [comment]
Thx! Sry for the late response, I've been overwhelmed. You can customize the loading of weights using the torch.load_state_dict() function.
